### ISSUE TITLE
Different formats support

### ISSUE THREAD

**Issue by talentlessguy** [daltonmenezes/electron-screen-recorder#1]
While webm is a nice choice for video, there are cases when I need to quickly send something, in either `gif` or `mp4`.

I think there should be a list of different formats to record videos:

* mp4
* gif
* webm
* webp
* apng

also, thanks for creating this! it's the only one linux screen recorder that isn't ugly

**Comment by daltonmenezes** [comment]
@talentlessguy Done! Thanks for enjoying this project and for the suggestion :D
