### ISSUE TITLE
[enhancement] Add a portable version for Windows

### ISSUE THREAD

**Issue by Bellisario** [daltonmenezes/electron-screen-recorder#13]
Actually, there isn't a Windows portable version, yet.

Please, add a portable version: I'd like to test the app features but without installing it.

**Comment by daltonmenezes** [comment]
@Bellisario Done, please check the [v.2.1.1 release](https://github.com/daltonmenezes/electron-screen-recorder/releases/tag/v2.1.1) 😀

**Comment by Bellisario** [comment]
Ok, thank you @daltonmenezes!
